wdController 1.5: undervoltage management.

diff --git a/arancino-rpi-scripts/files/usr/bin/wdController b/arancino-rpi-scripts/files/usr/bin/wdController
--- a/arancino-rpi-scripts/files/usr/bin/wdController
+++ b/arancino-rpi-scripts/files/usr/bin/wdController
@@ -1,16 +1,26 @@
 #!/bin/ash
 
-# wdController v1.4
+# wdController v1.5
+
+TEST=0
+CHECK="rw"
 
 ubus call system watchdog '{"magicclose": true}'
 ubus call system watchdog '{"stop": true}'
 
-while lsblk -f --output NAME,TYPE,STATE | grep disk > /dev/null; do
 
-   # date 1>&2
-   echo -n "X"
-   sleep 3
+while [ "$CHECK" != "ro" ] && [ $TEST = 0 ]; do
+
+    CHECK=`cat /proc/mounts | grep /dev/sda1 | awk '{print substr($4,1,2)}'`
+
+    lsblk -f --output NAME,TYPE,STATE | grep disk > /dev/null
+    TEST=`echo $?`
+
+    echo -n "X"
+
+    sleep 3
 
 done > /dev/watchdog
 
-echo "Reboot after IO failure" 1>&2
+
+echo "Reboot after IO failure"
